### ISSUE TITLE
disabled dropdown visually looks the same as a normal dropdown 

### ISSUE THREAD

**Issue by hannesdelbeke** [leixingyu/unrealStylesheet#4]
disabled dropdown visually looks the same as a normal dropdown

| unreal stylesheet | expected something like this |
| -- | -- |
| ![image](https://github.com/leixingyu/unrealStylesheet/assets/3758308/e6f9e9f7-f438-46b6-9553-33b9549997af) | ![image](https://github.com/leixingyu/unrealStylesheet/assets/3758308/456a6d28-9d52-48c4-b1a3-b4c09bac75e1) |

**Comment by hannesdelbeke** [comment]
adding this to the stylesheet fixes that
```CSS
QComboBox:disabled {
    color: #8f8f8f;
    background-color: #353535;
    border-style: transparent; }
```
